### ISSUE TITLE
Missing class Pattern

### ISSUE THREAD

**Issue by adispennette** [qos-ch/logback-audit#2]
I am using logback 1.1.2 libraries and the latest (0.6) logback-audit and I am getting the following error.

java.lang.NoClassDefFoundError: ch/qos/logback/core/joran/spi/Pattern
    at ch.qos.logback.audit.client.joran.JoranConfigurator.addInstanceRules(JoranConfigurator.java:38)
    at ch.qos.logback.core.joran.GenericConfigurator.buildInterpreter(GenericConfigurator.java:116)
    at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:146)
    at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
    at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
    at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
    at ch.qos.logback.audit.client.AuditorFactory.configureByResource(AuditorFactory.java:128)

I guess my first question is if this is still a live project?
If so is there a timeline on making this compatible with the latest logback-core?

Also I was curious about the AuditFactory and the use of pathPrefix in the auto config methods.
if I am putting the config on the class path and the application name is not a constant then the auto config fails.  I can get around this by using the resource loading method but the path prefix caught me off guard at first and I am wondering what the point of it is.

**Comment by pmalon** [comment]
1 year later and still no answer...
